### ISSUE TITLE
Some really cool addons

### ISSUE THREAD

**Issue by OrionCodeDev** [Johannes-Schneider/GoldDiff#1]
Hey Sir maybe you wanna do some graph about Team Gold Diff like from LEC. Also it's not working in spectator mode :/
That can be really cool tool for broadcast. Regards

**Comment by Johannes-Schneider** [comment]
Hi there,

thank you for your suggestion. Actually, I was alread planning to add a gold difference graph (like in the LEC).
I'm going to link the release/commit once this feature is implemented.

**Comment by Johannes-Schneider** [comment]
Hi @ChronoBrake 

within the latest release ([1.1.1](https://github.com/Johannes-Schneider/GoldDiff/releases/tag/1.1.1)), I included a bug fix for your problem with _GoldDiff_ not working in spectator mode.

I'll let you know once I also added the gold comparison graph.

**Comment by OrionCodeDev** [comment]
Hey any update about live gold charts? Regards

**Comment by Johannes-Schneider** [comment]
Hey @ChronoBrake 

really sorry for the long downtime, but I finally managed to [release version 1.3.0](https://github.com/Johannes-Schneider/GoldDiff/releases/tag/1.3.0), which also includes the new Gold Chart 🎉 (see the projects main page for a quick preview)

I will close this issue for now.
Please feel free to open up new issues should you encounter anything.
